document.getElementById("data").textContent = new Date().toLocaleDateString("pt-BR",{weekday:"long",year:"numeric",month:"long",day:"numeric"});
let talhoes=JSON.parse(localStorage.getItem("talhoes"))||[];let chart=null;let tipoGrafico="bar";let termoPesquisa="";
function mostrarAba(id){document.querySelectorAll(".aba").forEach(aba=>aba.classList.remove("ativa"));document.getElementById(id).classList.add("ativa");if(id==="abaRelatorios")gerarRelatorio();if(id==="abaRegistros")atualizarSelectTalhoes();}
function atualizarSelectTalhoes(){const select=document.getElementById("selectTalhao");if(!select)return;select.innerHTML="";talhoes.forEach((t,i)=>{const option=document.createElement("option");option.value=i;option.textContent=t.nome;select.appendChild(option);});}
function renderizarTalhoes(){const lista=document.getElementById("listaTalhoes");lista.innerHTML="";talhoes.filter(t=>t.nome.toLowerCase().includes(termoPesquisa.toLowerCase())).forEach((t,i)=>{const card=document.createElement("section");card.className="card";const titulo=document.createElement("h3");titulo.textContent=t.nome;card.appendChild(titulo);const resumo=document.createElement("p");resumo.innerHTML=`<strong>Total de Aplicações:</strong> ${t.aplicacoes.length} <br> <strong>Total Aplicado:</strong> ${t.aplicacoes.reduce((acc,ap)=>acc+ap.qtd,0)}g`;card.appendChild(resumo);const btnEditar=document.createElement("button");btnEditar.textContent="✏ Editar Talhão";btnEditar.onclick=()=>{const novoNome=prompt("Digite o novo nome do talhão:",t.nome);if(novoNome){t.nome=novoNome;salvar();}};const btnExcluir=document.createElement("button");btnExcluir.textContent="🗑 Excluir Talhão";btnExcluir.className="delete-btn";btnExcluir.onclick=()=>{if(confirm("Excluir este talhão e todas as aplicações?")){talhoes.splice(i,1);salvar();}};card.appendChild(btnEditar);card.appendChild(btnExcluir);lista.appendChild(card);});salvar();}
function salvar(){localStorage.setItem("talhoes",JSON.stringify(talhoes));}
document.getElementById("formTalhao").addEventListener("submit",e=>{e.preventDefault();const nome=document.getElementById("nomeTalhao").value.trim();if(!nome)return;talhoes.push({nome,aplicacoes:[]});document.getElementById("formTalhao").reset();salvar();renderizarTalhoes();});
document.getElementById("formAplicacao").addEventListener("submit",e=>{e.preventDefault();const talhaoIndex=document.getElementById("selectTalhao").value;const desc=document.getElementById("descAplicacao").value;const qtd=parseFloat(document.getElementById("qtdAplicacao").value);if(talhaoIndex===""||isNaN(qtd))return;talhoes[talhaoIndex].aplicacoes.push({desc,qtd,data:new Date().toISOString()});document.getElementById("formAplicacao").reset();salvar();});
document.getElementById("pesquisaTalhao").addEventListener("input",e=>{termoPesquisa=e.target.value;renderizarTalhoes();});
document.getElementById("toggleGrafico").addEventListener("click",()=>{tipoGrafico=tipoGrafico==="bar"?"pie":"bar";gerarRelatorio();});
document.getElementById("exportarPDF").addEventListener("click",()=>{const{jsPDF}=window.jspdf;const doc=new jsPDF("p","mm","a4");doc.setFontSize(18);doc.text("Relatório Geral - Grão Digital",14,20);doc.setFontSize(12);doc.text("Data: "+new Date().toLocaleDateString("pt-BR"),14,30);doc.text("Total de Talhões: "+document.getElementById("relTotalTalhoes").textContent,14,40);doc.text("Total de Aplicações: "+document.getElementById("relTotalAplicacoes").textContent,14,47);doc.text("Total de Insumos Aplicados: "+document.getElementById("relTotalInsumos").textContent,14,54);doc.text("Resumo por Talhão:",14,65);let y=72;document.querySelectorAll("#resumoTalhoes li").forEach(li=>{doc.text("- "+li.textContent,14,y);y+=7;});const canvas=document.getElementById("graficoInsumos");const imgData=canvas.toDataURL("image/png");doc.addImage(imgData,"PNG",14,y,180,100);doc.save("relatorio-grao-digital.pdf");});
function gerarRelatorio(){let totalTalhoes=talhoes.length;let totalAplicacoes=0;let totalInsumos=0;const resumo=document.getElementById("resumoTalhoes");resumo.innerHTML="";let labels=[];let dados=[];talhoes.forEach(t=>{totalAplicacoes+=t.aplicacoes.length;const totalTalhao=t.aplicacoes.reduce((acc,ap)=>acc+parseFloat(ap.qtd),0);totalInsumos+=totalTalhao;const li=document.createElement("li");li.textContent=`${t.nome}: ${t.aplicacoes.length} aplicações, ${totalTalhao}g aplicados`;resumo.appendChild(li);labels.push(t.nome);dados.push(totalTalhao);});document.getElementById("relTotalTalhoes").textContent=totalTalhoes;document.getElementById("relTotalAplicacoes").textContent=totalAplicacoes;document.getElementById("relTotalInsumos").textContent=totalInsumos+"g";const ctx=document.getElementById("graficoInsumos").getContext("2d");if(chart)chart.destroy();chart=new Chart(ctx,{type:tipoGrafico,data:{labels:labels,datasets:[{label:"Insumos aplicados (g)",data:dados,backgroundColor:["rgba(78,52,46,0.7)","rgba(100,181,246,0.7)","rgba(129,199,132,0.7)","rgba(255,241,118,0.7)","rgba(244,143,177,0.7)"]}]},options:{responsive:true,plugins:{legend:{display:true}}}});}
renderizarTalhoes();if("serviceWorker"in navigator)navigator.serviceWorker.register("service-worker.js");